## Numpy - Projects

In [1]:
import numpy as np
print(np.__version__) # we want to know the version of the numpy 

2.1.2


In [2]:
import numpy as np
my_list = [1,2,3,4,5]
my_array = np.array(my_list)
print(my_list)
print(my_array)


[1, 2, 3, 4, 5]
[1 2 3 4 5]


## To know the value in any index

In [3]:
import numpy as np
a = np.array(10)
b = np.array([10,20])
c = np.array([[1,2],[3,4]])
d = np.array ([[[3,4],[5,6]],[[1,2],[8,9]]])
print(d[1][1][1])
print(d[1,1,1])

9
9


## To know how many dimensions in array 

In [4]:
print(d.ndim)

3


## To custom dimensions in the array 

In [5]:
my_custom_array = np.array([1,2,3], ndmin=3)
print(my_custom_array.ndim)
print(my_custom_array)

3
[[[1 2 3]]]


## To Know the different between arraies and the memory 

In [6]:
import numpy as np 
my_list = [1,2,3,4,5,6,7]
my_array = np.array(my_list)
print(id(my_list[0]))
print(id(my_list[1]))
print(id(my_array[0]))
print(id(my_array[1]))

140726839206824
140726839206856
2753699770960
2753699770960


In [7]:
import numpy as np
my_list = [1,2,3,"Abdallah",True]
my_array = np.array(my_list)
print(type(my_list[0]))
print(type(my_array[0]))

<class 'int'>
<class 'numpy.str_'>


## To know the performance and the speed and the memory 

In [8]:
import time 
import sys
elements = 150 
my_array1 = np.arange(elements)
my_array2 = np.arange(elements)
print(my_array)
start_array = time.time()
sum_array = my_array1 + my_array2
print(sum_array)
print((time.time())-(start_array))


['1' '2' '3' 'Abdallah' 'True']
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214
 216 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250
 252 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286
 288 290 292 294 296 298]
0.0006518363952636719


In [9]:
import numpy as np 
my_array = np.arange(100)
print(my_array)
print(my_array.itemsize)
print(my_array.size)
print((my_array.itemsize)*(my_array.size))
my_list = range (100)
print(sys.getsizeof(1))
print(len(my_list))
print((sys.getsizeof(1))*(len(my_list)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
8
100
800
28
100
2800


Slicing arrays

In [10]:
import numpy as np 
A = np.array(["A","B","C","D","E","F"])
print(A.ndim)
print(A[1])
print(A[1:4])
print(A[:4])
print(A[2:])
print("*" * 50)

B =np.array([["A","B","C"],["X","D","Y"],["E","F","Z"],["M","N","O"]])
print(B.ndim)
print(B[1])
print(B[0:3])
print(B[:3])
print(B[:3 , :2])
print(B[2: , 0])
print(B[2: , :2:2])

1
B
['B' 'C' 'D']
['A' 'B' 'C' 'D']
['C' 'D' 'E' 'F']
**************************************************
2
['X' 'D' 'Y']
[['A' 'B' 'C']
 ['X' 'D' 'Y']
 ['E' 'F' 'Z']]
[['A' 'B' 'C']
 ['X' 'D' 'Y']
 ['E' 'F' 'Z']]
[['A' 'B']
 ['X' 'D']
 ['E' 'F']]
['E' 'M']
[['E']
 ['M']]


## Data Types and Control arrays

In [11]:
import numpy as np 
my_array = np.array([1,2,3] , dtype=float)
print(my_array)
print(my_array.dtype)
my_array2 = np.array([1,2,3,4,5,6,7])
print(my_array2.dtype)
print(my_array2)
my_array3 = my_array2.astype(float)
print(my_array3.dtype)
print(my_array3)

[1. 2. 3.]
float64
int64
[1 2 3 4 5 6 7]
float64
[1. 2. 3. 4. 5. 6. 7.]


## Test Capacity

In [12]:
import numpy as np
my_array  = np.array([100,200,300,400] , dtype=float)
print(my_array.dtype)
print(my_array.itemsize)
my_array2 = my_array.astype(int)
print(my_array2.dtype)
print(my_array2.itemsize)

float64
8
int64
8


## Arthemitic Operations 

In [13]:
import numpy as np 
My_array1 = np.array([10,20,30])
My_array2 = np.array([5,2,4])
print(My_array1 + My_array2)
print(My_array1 - My_array2)
print(My_array1 * My_array2)
print(My_array1 / My_array2)
print("*" *50)
My_array3 = np.array([[1,4],[5,9]])
My_array4 = np.array([[2,7],[10,5]])
print(My_array3 + My_array4)
print(My_array3 - My_array4)
print(My_array3 * My_array4)
print(My_array3 / My_array4)


[15 22 34]
[ 5 18 26]
[ 50  40 120]
[ 2.  10.   7.5]
**************************************************
[[ 3 11]
 [15 14]]
[[-1 -3]
 [-5  4]]
[[ 2 28]
 [50 45]]
[[0.5        0.57142857]
 [0.5        1.8       ]]


## Ravel Method 

In [14]:
My_array  = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(My_array.ndim)
print(My_array.ravel())

3
[1 2 3 4 5 6 7 8 9]


## Shape & Reshape 

In [1]:
import numpy as np 
my_array = np.array([1,2,3,4])
print(my_array.shape)
my_array2 = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(my_array2.shape)
My_array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
Reshaped_array = My_array1.reshape(2,6)
print(Reshaped_array)
Reshaped_array2 = My_array1.reshape(3,2,2)
print(Reshaped_array2)
print(Reshaped_array2.ndim)











(4,)
(3, 4)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3


In [16]:
import pandas as pd 
import numpy as np
dict = {
    "First score " : [100,90,np.nan,95],
    "second score " : [30,45,56,np.nan],
    "third score" : [np.nan ,40,80,98] }
df = pd.DataFrame(dict)
df.fillna(0)
print(df.fillna(0))

   First score   second score   third score
0         100.0           30.0          0.0
1          90.0           45.0         40.0
2           0.0           56.0         80.0
3          95.0            0.0         98.0


In [17]:
import pandas as pd
import numpy as np
dict = {
    "first score " :[100,90,np.nan,95],
    "second score" :[30,np.nan,45,56],
    "third score " :[52,40,80,98],
    "fourth score" :[np.nan,np.nan,np.nan,65]
}
df = pd.DataFrame(dict)
df
print(df.dropna())

   first score   second score  third score   fourth score
3          95.0          56.0            98          65.0


In [18]:
import numpy as np 
np.array([1,2,3,4])
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])